### ISSUE TITLE
REST api url has duplicate question mark

### ISSUE THREAD

**Issue by rajakannan** [sheriallis/where-in-the-world#3]
Congrats @sheriallis , this project looks awesome and very clean code :+1: :100:

May be a  minor issue:

REST API call to fetch countries has two **?** that gives unexpected result.

### **Reproduce:** 
**step 1:**
open chrome Dev tool

**step 2:**
go to [Afghanistan](https://srd-whereintheworld.netlify.com/country/Afghanistan)

**step 3:** 
check the ajax url made to fetch country details

**response:**
`https://restcountries.eu/rest/v2/name/Afghanistan?fullText=true?fields=name;flag;nativeName;population;region;subregion;capital;topLevelDomain;currencies;languages;borders`

It has the symbol **?** twice, which gives us two issues

**issue 1:** while we expect only the requested fields from rest API, it returns all the fields

**issue 2:** If you click the country [India](https://srd-whereintheworld.netlify.com/country/India) we get the response of **British Indian Ocean Territory** not India that is because of the wrong URL

@sheriallis  Can I give you a new PR for this issue please.?

**Comment by sheriallis** [comment]
Thank you, your pull request has been merged.😀
